
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "oyzgptyrgofrwhqaitnx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[api.cors]
enabled = true
config.allowed_origins = ["*"]
config.allowed_methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
config.allowed_headers = ["Authorization", "X-Client-Info", "X-Forwarded-For", "X-Supabase-Auth-Token", "Content-Type"]

[db]
port = 54322

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 30

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions]
enabled = true
port = 54326

# Turn off JWT verification for the Stripe webhook function
[functions.stripe-webhook]
verify_jwt = false

[inbucket]
enabled = true
port = 54327

[vector]
enabled = true
port = 54328
