// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyzgptyrgofrwhqaitnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95emdwdHlyZ29mcndocWFpdG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODkwMTUsImV4cCI6MjA1OTI2NTAxNX0.2xyiZONxThwvswPlLHmR_8v4xM7JcjH_tyGSHAf8lXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);